# microservicecloud-config
microservicecloud-config demo
spring:
      profiles:
        active:
          - dev
---
spring:
     profiles: dev
        application:
             name: microservicecloude-config-zjy-dev
---
spring:
      profiles: test
          application:
                  name: microservicecloude-config-zjy-test
